site_name: XSC Learning Notes

site_url: https://crazy-squirrel.github.io/mkdocs-xsc

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - toc.follow
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode    
      primary: teal
      accent: teal

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/crazy-squirrel

nav:
  - Home: index.md
  - Paper Reading:
    - Paper Reading/index.md
    - Chp1: Paper Reading/Chp1.md
    - Chp2: Paper Reading/Chp2.md
    - Chp3: Paper Reading/Chp3.md
  - Digital IC:
    - Digital IC/index.md
    - Chp1: Digital IC/Chp1.md
    - Chp2: Digital IC/Chp2.md
    - Chp3: Digital IC/Chp3.md
  - Verilog:
    - Verilog/index.md
    - Chp1: Verilog/Chp1.md
    - Chp2: Verilog/Chp2.md
    - Chp3: Verilog/Chp3.md
  - About Me: about.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - tables

copyright: |
  &copy; 2023 <a href="https://github.com/crazy-squirrel"  target="_blank" rel="noopener">Songchen Xu</a>